####
# mvn package -Pnative -Dnative-image.docker-build=true
# docker build -f src/main/docker/Dockerfile.native -t quarkus/quarkus-movie .
# docker run -i --rm -p 8080:8080 quarkus/quarkus-movie
###

FROM registry.access.redhat.com/ubi8/ubi-minimal
ENV LD_LIBRARY_PATH=/usr/local/lib64
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]